[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
anyhow = { workspace = true }
